# CLI tools
brew "ast-grep"
brew "cmake"
brew "colima"
brew "docker"
brew "docker-buildx"
brew "docker-compose"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "gitleaks"
brew "go"
brew "jq"
brew "jupyterlab"
brew "lua"
brew "mas"
brew "mise"
brew "postgresql@16"
brew "ripgrep"
brew "shellcheck"
brew "uv"
brew "yq"

# Developer applications. Docker Desktop is intentionally not installed;
# Colima provides the local Docker runtime used with the CLI above.
cask "cursor"
cask "ghostty"
cask "zed"
cask "rider"
cask "codex"
cask "github"
cask "lm-studio"
cask "chatgpt"
cask "chatgpt-atlas"
cask "claude"
cask "notion"
cask "obsidian"
cask "google-chrome"
cask "firefox"
cask "vivaldi"
cask "rectangle"
cask "mos"
cask "love"
cask "blender"

# Xcode
mas "Xcode", id: 497799835
